spring:
  application:
    name: iplatform-moex
  datasource:
    driverClassName: org.postgresql.Driver
    username: @db-username@
    password: @db-password@
    url: @db-url@
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: false
  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: basic