#  ISS Queries

securities: https://iss.moex.com/iss/securities.json?iss.meta=off&iss.only=data&iss.json=extended
#  Список бумаг торгуемых на московской бирже.

security: https://iss.moex.com/iss/securities/[security].json?iss.meta=off&iss.json=extended
#  Получить спецификацию инструмента. Например: https://iss.moex.com/iss/securities/IMOEX.xml

aggregates: https://iss.moex.com/iss/securities/[security]/aggregates.json?iss.meta=off&iss.only=data&iss.json=extended
#  Агрегированные итоги торгов за дату по рынкам

indices: https://iss.moex.com/iss/securities/[security]/indices.json?iss.meta=off&iss.only=data&iss.json=extended&only_actual=1
#  Список индексов в которые входит бумага

secstats: https://iss.moex.com/iss/engines/[engine]/markets/[market]/secstats.json?iss.meta=off&iss.only=engines&iss.json=extended
#  Промежуточные "Итоги дня". Только для фондового рынка

engines: https://iss.moex.com/iss/engines.json?iss.meta=off&iss.only=data&iss.json=extended
#  Получить доступные торговые системы. Например: https://iss.moex.com/iss/engines.xml

engine: https://iss.moex.com/iss/engines/[engine].json?iss.meta=off&iss.json=extended&iss.only=[param]
#  Получить описание и режим работы торговой системы. Например: https://iss.moex.com/iss/engines/stock.xml
