package space.eliseev.iplatformmoex.enums;

public enum SecurityGroup {
    STOCK_INDEX, STOCK_SHARES, STOCK_BONDS, CURRENCY_SELT, FUTURES_FORTS, FUTURES_OPTIONS, STOCK_DR,
    STOCK_FOREIGN_SHARES, STOCK_EUROBOND, STOCK_PPIF, STOCK_ETF, CURRENCY_METAL, STOCK_QNV, STOCK_GCC,
    STOCK_DEPOSIT, CURRENCY_FUTURES, CURRENCY_INDICES, STOCK_MORTGAGE
}
